### ISSUE TITLE
FeaturedPackageView GET button's color is hard-coded.

### ISSUE THREAD

**Issue by Shugabuga** [Parcility/Kennel#11]
Ideal behavior: Respecting the default or root tintColor.

Actual: [It's hard-coded.](https://github.com/ZenithDevs/Kennel/blob/800342ff8ac7bbabe7659c6f19d63b51ffbe0069/src/kennel.css#L433)

**Comment by magnetardev** [comment]
Sileo no longer seems to support having FeaturedBannerView in a depiction, so is not in v2 and should be a non-issue.
