### ISSUE TITLE
Not on NPM

### ISSUE THREAD

**Issue by WilsontheWolf** [Parcility/Kennel#13]
I was attempting to install the module but it doesn't seem to be on npm (or at least public). If you could fix this that would be lovely. Thanks

**Comment by GunnerBasil** [comment]
Same issue here

**Comment by WilsontheWolf** [comment]
I found you can install it directly from github using `yarn add @zenithdevs/kennel` or `npm i @zenithdevs/kennel`

Hope this helps

**Comment by magnetardev** [comment]
Now is on npm, as `@parcility/kennel`
